"use client";
import { useEffect, useState } from "react";
import { statusLabels, money, dateTime, type Snapshot } from "@/lib/baile/types";
import { Empty, Stat, Form, Field, Receipt, type Run } from "./ui";
import { CategoryForm, JudgeForm, CompetitionList, Results } from "./Competition";
import { Registers } from "./Registers";
import { EnrollmentsDesk, MusicDesk, Ledger, AccreditationDesk } from "./AdminOperations";
import { ScheduleDesk } from "./ScheduleDesk";
const modules = [
  { name: "Resumen", id: "resumen", detail: "Una vista general del evento y las tareas pendientes." },
  { name: "Registros", id: "registros", detail: "Perfiles de participantes y estado del Full Pass." },
  { name: "Inscripciones", id: "inscripciones", detail: "Competidores, categorías y pagos independientes." },
  { name: "Pagos", id: "pagos", detail: "Validación individual de los comprobantes recibidos." },
  { name: "Acreditación", id: "acreditacion", detail: "Control de ingreso y códigos de manilla." },
  { name: "Contabilidad", id: "contabilidad", detail: "Valores inscritos, comprobantes aprobados y pendientes." },
  { name: "Música", id: "musica", detail: "Pistas organizadas por categoría y número de competencia." },
  { name: "Minuto a minuto", id: "programa", detail: "Horarios, escenarios y estados de la competencia." },
  { name: "Categorías", id: "categorias", detail: "Modalidades, divisiones, tarifas y plazos." },
  { name: "Jurados", id: "jurados", detail: "Accesos independientes y control de calificaciones." },
  { name: "Resultados", id: "resultados", detail: "Puntuaciones, posiciones y resultados por categoría." },
  { name: "Ajustes", id: "ajustes", detail: "Nombre, tarifas, instrucciones y apertura de inscripciones." },
];
export function Admin({ s, run, refresh }: { s: Snapshot; run: Run; refresh: () => Promise<void> }) {
  const [tab, setTab] = useState("Resumen"); const [query, setQuery] = useState(""); const [cat, setCat] = useState(""); const [status, setStatus] = useState(""); const [kind, setKind] = useState("");
  const normalized = (v: string) => v.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
  const controls = <div className="dance-filters"><input aria-label="Buscar participante" placeholder="Nombre, documento, academia o ciudad…" value={query} onChange={e => setQuery(e.target.value)} /><select aria-label="Filtrar categoría" value={cat} onChange={e => setCat(e.target.value)}><option value="">Todas las categorías</option>{s.categories.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select><select aria-label="Filtrar estado" value={status} onChange={e => setStatus(e.target.value)}><option value="">Todos los estados</option>{Object.entries(statusLabels).map(([v, l]) => <option value={v} key={v}>{l}</option>)}</select></div>;
  const payments = s.payments.filter(p => { const person = s.participants.find(x => x.id === p.participantId)!; return normalized(`${person.name} ${person.document} ${person.city} ${person.academy} ${person.code}`).includes(normalized(query)) && (!status || p.status === status) && (!kind || p.kind === kind) && (!cat || s.enrollments.some(e => e.id === p.enrollmentId && e.categoryId === cat)); });
  const [personId, setPersonId] = useState<string | null>(null);
  useEffect(() => {
    const sync = () => setTab(modules.find(m => m.id === window.location.hash.slice(1))?.name || "Resumen");
    sync(); window.addEventListener("hashchange", sync);
    return () => window.removeEventListener("hashchange", sync);
  }, []);
  const goTab = (name: string) => { setTab(name); window.location.hash = modules.find(m => m.name === name)!.id; };
  const openPerson = (id: string) => { setPersonId(id); goTab("Registros"); };
  const current = modules.find(m => m.name === tab)!;
  const counts: Record<string, number> = { Registros: s.participants.length, Inscripciones: s.enrollments.length, Pagos: s.payments.filter(p => p.status === "pending").length };
  return <section className="dance-admin-shell">
    <aside className="dance-admin-nav"><div className="dance-admin-nav-title"><span className="dance-eyebrow">ORGANIZACIÓN</span><strong>Centro de control</strong><small>{s.settings.name}</small></div><nav aria-label="Módulos administrativos">{modules.map((m, i) => <a key={m.id} href={`#${m.id}`} aria-current={tab === m.name ? "page" : undefined} className={tab === m.name ? "active" : ""} onClick={() => setTab(m.name)}><span className="dance-nav-number">{String(i + 1).padStart(2, "0")}</span><span>{m.name}</span>{counts[m.name] !== undefined && <small>{counts[m.name]}</small>}</a>)}</nav><p className="dance-muted">Los cambios de validación, acreditación y tarima quedan en el historial.</p></aside>
    <div className="dance-admin-workspace"><div className="dance-admin-title"><div><p className="dance-eyebrow">CENTRO DE CONTROL / {tab}</p><h1>{tab === "Resumen" ? "Tu evento, bajo control." : tab}</h1><p>{current.detail}</p></div><button className="dance-btn secondary small" onClick={() => refresh().catch(() => window.location.reload())}>Actualizar datos</button></div>
    {tab === "Resumen" && <><div className="dance-stats"><Stat label="Participantes" value={s.participants.length} /><Stat label="Full Pass aprobados" value={s.payments.filter(p => p.kind === "fullpass" && p.status === "approved").length} /><Stat label="Pendientes de aprobación" value={s.participants.filter(p => !["approved", "rejected"].includes(s.payments.find(x => x.participantId === p.id && x.kind === "fullpass")?.status || "pending")).length} /><Stat label="Full Pass rechazados" value={s.payments.filter(p => p.kind === "fullpass" && p.status === "rejected").length} /></div><div className="dance-two-columns"><div className="dance-panel"><h2>El pulso de la competencia</h2>{s.categories.map(c => <div className="dance-list-row" key={c.id}><span>{c.name}</span><strong>{s.enrollments.filter(e => e.categoryId === c.id).length} inscritos</strong></div>)}</div><div className="dance-panel dark"><p className="dance-eyebrow">POR REVISAR</p><h2>{s.payments.filter(p => p.status === "pending").length} comprobantes</h2><p>Valida cada Full Pass y cada categoría individualmente para habilitar a los competidores.</p><button className="dance-btn" onClick={() => { setStatus("pending"); goTab("Pagos"); }}>Revisar pagos ↗</button></div></div>{s.settings.demo && !s.exampleCreated && <div className="dance-panel"><h2>Prueba el recorrido completo</h2><p>Crea dos participantes ficticios, un Full Pass pendiente, una categoría aprobada y tres jurados. Recibirás sus accesos para recorrer cada pantalla.</p><Form action="example" run={run} label="Crear recorrido de ejemplo"><span /></Form></div>}<div className="dance-panel"><h2>Actividad reciente</h2>{!s.audit.length && <Empty>Aquí aparecerá el historial de registros, pagos y notas.</Empty>}{s.audit.slice(0, 12).map(a => <div className="dance-list-row" key={a.id}><span>{a.action}<small>{s.judges.find(j => j.id === a.actor)?.name || s.participants.find(p => p.id === a.actor)?.name || "Organización"}</small></span><time>{dateTime(a.at)}</time></div>)}</div></>}
    {tab === "Registros" && <Registers s={s} run={run} selectedId={personId} onSelect={setPersonId} />}
    {tab === "Inscripciones" && <EnrollmentsDesk s={s} onPerson={openPerson} />}
    {tab === "Música" && <MusicDesk s={s} />}
    {tab === "Contabilidad" && <Ledger s={s} />}
    {tab === "Acreditación" && <AccreditationDesk s={s} run={run} />}
    {tab === "Minuto a minuto" && <ScheduleDesk s={s} run={run} />}
    {tab === "Pagos" && <>{controls}<div className="dance-filters"><select aria-label="Tipo de pago" value={kind} onChange={e => setKind(e.target.value)}><option value="">Full Pass y categorías</option><option value="fullpass">Solo Full Pass</option><option value="category">Solo categorías</option></select><span>{payments.length} comprobantes</span></div>{!payments.length && <Empty>No hay comprobantes en esta selección.</Empty>}{payments.map(p => <div className="dance-panel" key={p.id}><div className="dance-panel-title"><div><p className="dance-eyebrow">{p.kind === "fullpass" ? "PAGO GENERAL / FULL PASS" : "PAGO DE CATEGORÍA"}</p><h2>{s.participants.find(x => x.id === p.participantId)?.name}</h2><p>{p.kind === "category" ? s.categories.find(c => c.id === s.enrollments.find(e => e.id === p.enrollmentId)?.categoryId)?.name : "Habilitación al evento"}</p></div><strong className="dance-payment-amount">{money(p.amount)}</strong></div><Receipt payment={p} /><Form action="review" run={run} label="Guardar validación"><input name="paymentId" type="hidden" value={p.id} /><div className="dance-form-grid"><Field label="Resultado de revisión" name="status"><select name="status" defaultValue={p.status}>{Object.entries(statusLabels).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></Field><Field label="Observación (obligatoria si se rechaza)" name="note" required={false} value={p.note} maxLength={1000} /></div></Form>{p.reviewedAt && <p className="dance-muted">Última revisión: {dateTime(p.reviewedAt)}</p>}</div>)}</>}
    {tab === "Categorías" && <><details className="dance-panel"><summary>Crear categoría</summary><CategoryForm run={run} /></details>{s.categories.map(c => <div className="dance-panel" key={c.id}><div className="dance-panel-title"><div><p className="dance-eyebrow">{c.rhythm} · {c.modality} · {c.division}</p><h2>{c.name}</h2></div><strong>{money(c.fee)}</strong></div><p>{s.enrollments.filter(e => e.categoryId === c.id).length} inscritos · {c.active ? "Disponible" : "Cerrada a nuevas inscripciones"}</p><details><summary>Editar categoría y plazo de pistas</summary><CategoryForm c={c} run={run} /></details><CompetitionList s={s} categoryId={c.id} /></div>)}</>}
    {tab === "Jurados" && <><div className="dance-callout">Cada jurado tiene una cuenta individual. Las notas enviadas quedan bloqueadas hasta que autorices su edición.</div><details className="dance-panel"><summary>Crear acceso de jurado</summary><JudgeForm s={s} run={run} /></details>{s.judges.map(j => <details className="dance-panel" key={j.id}><summary>{j.name} · {j.email}</summary><JudgeForm s={s} run={run} judge={j} /></details>)}<div className="dance-panel"><h2>Calificaciones enviadas</h2>{!s.scores.length && <Empty>Los jurados todavía no han enviado calificaciones.</Empty>}{s.scores.map(x => { const e = s.enrollments.find(e => e.id === x.enrollmentId)!; return <details className="dance-inline-card" key={x.id}><summary>{s.judges.find(j => j.id === x.judgeId)?.name} · N.º {String(e.competitionNumber).padStart(3, "0")} · {s.categories.find(c => c.id === e.categoryId)?.name} · {x.locked ? "Bloqueada" : "Edición autorizada"}</summary><p>{x.values.join(" / ")} · Total: {x.values.reduce((a, b) => a + b, 0).toFixed(2)}</p><p>Enviada: {dateTime(x.submittedAt)}</p>{x.locked && <Form action="unlock" run={run} label="Autorizar edición"><input name="scoreId" type="hidden" value={x.id} /><Field label="Motivo de la autorización" name="note" maxLength={500} /></Form>}</details>; })}</div></>}
    {tab === "Resultados" && <Results s={s} />}
    {tab === "Ajustes" && <div className="dance-panel"><h2>Configura tu evento</h2><Form action="settings" run={run} label="Guardar configuración"><div className="dance-form-grid"><Field label="Nombre del evento" name="name" value={s.settings.name} maxLength={100} /><Field label="Frase del evento" name="tagline" value={s.settings.tagline} maxLength={200} /><Field label="Valor Full Pass (COP)" name="fullPassFee" type="number" min={1} value={s.settings.fullPassFee} /><Field label="Fórmula de resultados" name="formula"><select name="formula" defaultValue={s.settings.formula}><option value="average">Promedio de todos los criterios y jurados (1–10)</option><option value="sum">Suma de todos los criterios y jurados</option></select></Field></div><Field label="Instrucciones de pago" name="paymentInstructions"><textarea name="paymentInstructions" required maxLength={3000} rows={5} defaultValue={s.settings.paymentInstructions} /></Field><label className="dance-check"><input type="checkbox" name="registrationOpen" defaultChecked={s.settings.registrationOpen} /> Registros generales abiertos</label><label className="dance-check"><input type="checkbox" name="categoryRegistrationOpen" defaultChecked={s.settings.categoryRegistrationOpen} /> Inscripciones a categorías abiertas</label><p className="dance-muted">Cada criterio tiene el mismo peso. Solo se asignan posiciones cuando están todas las notas bloqueadas de los jurados asignados. Los empates comparten posición.</p></Form></div>}
  </div></section>;
}
