"use client";
import { useState } from "react";
import type { Snapshot, Category, PublicUser } from "@/lib/baile/types";
import { ranking } from "@/lib/baile/results";
import { Field, Form, Empty, Music, exportCsv, type Run } from "./ui";
export function CategoryForm({ c, run }: { c?: Category; run: Run }) {
  const date = c?.deadline ? new Date(Date.parse(c.deadline) - 5 * 3600000).toISOString().slice(0, 16) : "";
  const adjustedRun: Run = (action, f) => { const d = String(f.get("deadline") || ""); if (d) f.set("deadline", `${d}:00-05:00`); return run(action, f); };
  return <Form action="category" run={adjustedRun}><input type="hidden" name="id" value={c?.id || ""} /><div className="dance-form-grid"><Field name="name" label="Nombre" value={c?.name} maxLength={120} /><Field name="rhythm" label="Ritmo" value={c?.rhythm} maxLength={80} /><Field name="modality" label="Modalidad"><select name="modality" defaultValue={c?.modality || "Solista"}><option>Solista</option><option>Pareja</option><option>Grupo</option></select></Field><Field name="division" label="División" value={c?.division || "Abierta"} maxLength={80} /><Field name="fee" label="Valor de inscripción (COP)" type="number" min={1} value={c?.fee || 60000} /><Field name="deadline" label="Plazo de pistas (hora de Colombia)" type="datetime-local" value={date} required={false} /></div><label className="dance-check"><input type="checkbox" name="active" defaultChecked={c?.active ?? true} /> Disponible para nuevas inscripciones</label></Form>;
}
export function JudgeForm({ s, run, judge }: { s: Snapshot; run: Run; judge?: PublicUser }) {
  return <Form action="judge" run={run}><input type="hidden" name="id" value={judge?.id || ""} /><div className="dance-form-grid"><Field name="name" label="Nombre del jurado" value={judge?.name} maxLength={120} /><Field name="email" label="Correo" type="email" value={judge?.email} /><Field name="password" label={judge ? "Nueva contraseña (deja vacío para conservarla)" : "Contraseña inicial"} type="password" required={!judge} minLength={10} maxLength={160} /></div><p>Categorías asignadas</p><div className="dance-checks">{s.categories.map(c => <label className="dance-check" key={c.id}><input type="checkbox" name="categories" value={c.id} defaultChecked={judge?.categories.includes(c.id)} />{c.name}</label>)}</div></Form>;
}
export function CompetitionList({ s, categoryId }: { s: Snapshot; categoryId: string }) {
  const rows = ranking(s, categoryId).sort((a, b) => a.enrollment.competitionNumber! - b.enrollment.competitionNumber!);
  const name = s.categories.find(c => c.id === categoryId)?.name || "categoría";
  return <><div className="dance-panel-title"><h3>Listado oficial</h3><button className="dance-btn secondary small" onClick={() => exportCsv(`listado-${categoryId}.csv`, [["Categoría", "Número", "Inscripción", "Participante / equipo", "Integrantes", "Pista"], ...rows.map(({ enrollment: e }) => [name, e.competitionNumber, e.code, e.team || s.participants.find(p => p.id === e.participantId)?.name || "", e.members, e.musicName || "Pendiente"])])}>Descargar listado</button></div>{rows.length ? rows.map(({ enrollment: e }) => <div className="dance-inline-card" key={e.id}><strong>N.º {String(e.competitionNumber).padStart(3, "0")} · {e.team || s.participants.find(p => p.id === e.participantId)?.name}</strong><p>{e.code} · {e.members}</p><Music e={e} /></div>) : <Empty>El listado se genera al aprobar los pagos de las categorías.</Empty>}</>;
}
export function Results({ s }: { s: Snapshot }) {
  const [cat, setCat] = useState(s.categories[0]?.id || ""); const rows = ranking(s, cat); const judges = s.judges.filter(j => j.categories.includes(cat));
  return <div className="dance-panel"><div className="dance-panel-title"><div><p className="dance-eyebrow">PUNTUACIONES Y POSICIONES</p><h2>El resultado de cada presentación.</h2></div><select aria-label="Categoría de resultados" value={cat} onChange={e => setCat(e.target.value)}>{s.categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div><p>{s.settings.formula === "average" ? "Promedio por criterio y jurado, escala de 1 a 10." : "Suma de los puntos de todos los criterios y jurados."} Empates: misma posición. Las notas incompletas no tienen posición. Las posiciones son provisionales mientras falten presentaciones por calificar.</p><button className="dance-btn secondary small" onClick={() => exportCsv(`resultados-${cat}.csv`, [["Posición", "Número", ...judges.map(j => j.name), "Total", "Promedio", "Estado"], ...rows.map(r => [r.position, r.enrollment.competitionNumber, ...r.totals, r.total, r.average?.toFixed(2) || "", r.complete ? "Completo" : "Pendiente"])])}>Descargar resultados</button><div className="dance-table-wrap"><table><thead><tr><th>Posición</th><th>Competidor</th>{judges.map(j => <th key={j.id}>{j.name}<small>/ 60 puntos</small></th>)}<th>Total</th><th>Promedio</th><th>Estado</th></tr></thead><tbody>{rows.map(r => <tr key={r.enrollment.id} className={r.position === 1 ? "winner" : ""}><td>{r.position === null ? "—" : `#${r.position}`}</td><td><strong>N.º {String(r.enrollment.competitionNumber).padStart(3, "0")}</strong><small>{r.enrollment.team || s.participants.find(p => p.id === r.enrollment.participantId)?.name}</small></td>{r.totals.map((v, i) => <td key={i}>{v?.toFixed(2) ?? "Pendiente"}</td>)}<td>{r.total.toFixed(2)}</td><td>{r.average?.toFixed(2) ?? "Pendiente"}</td><td>{r.complete ? "Completo" : `${r.received}/${r.expected} jurados`}</td></tr>)}</tbody></table></div>{!rows.length && <Empty>No hay competidores habilitados en esta categoría.</Empty>}{judges.length === 0 && <div className="dance-callout">Asigna jurados a esta categoría para comenzar a calificar.</div>}</div>;
}
export function ParticipantResults({ s, participantId }: { s: Snapshot; participantId: string }) {
  const categories = s.categories.filter(c => s.enrollments.some(e => e.participantId === participantId && e.categoryId === c.id));
  if (!categories.length) return null;
  return <section className="dance-inline-card"><h3>Calificaciones y posiciones</h3>{categories.map(c => {
    const row = ranking(s, c.id).find(r => r.enrollment.participantId === participantId);
    if (!row) return <p key={c.id}>{c.name}: pendiente de habilitación.</p>;
    const judges = s.judges.filter(j => j.categories.includes(c.id));
    return <div key={c.id}><h4>{c.name}</h4><p>{judges.map((j, i) => `${j.name}: ${row.totals[i]?.toFixed(2) ?? "pendiente"}`).join(" · ") || "Sin jurados asignados"}</p><p>Total: {row.total.toFixed(2)} · Promedio: {row.average?.toFixed(2) ?? "pendiente"} · Posición actual: {row.position ? `#${row.position}` : "pendiente"}</p><small>La posición puede variar hasta completar todas las presentaciones.</small></div>;
  })}</section>;
}
