"use client";
import { useState } from "react";
import { CRITERIA, dateTime, type Snapshot, type Enrollment } from "@/lib/baile/types";
import { Heading, Empty, Stat, Form, type Run } from "./ui";
export function Judge({ s, run }: { s: Snapshot; run: Run }) {
  const [cat, setCat] = useState(s.categories[0]?.id || ""); const entries = s.enrollments.filter(e => e.categoryId === cat); const ownScores = s.scores.filter(x => x.locked);
  return <section className="dance-container dance-section"><Heading eyebrow={`MESA DE JURADOS / ${s.user?.name}`} title="Tu criterio hace la diferencia." detail="Evalúa cada presentación de forma independiente. Cada criterio se califica de 1 a 10." /><div className="dance-stats"><Stat label="Mis categorías" value={s.categories.length} /><Stat label="Notas enviadas" value={ownScores.length} /><Stat label="Por calificar" value={s.enrollments.filter(e => !ownScores.some(x => x.enrollmentId === e.id)).length} /></div><div className="dance-tabs" role="tablist" aria-label="Categorías asignadas">{s.categories.map(c => <button key={c.id} role="tab" aria-selected={c.id === cat} className={c.id === cat ? "active" : ""} onClick={() => setCat(c.id)}>{c.name}</button>)}</div>{!entries.length && <Empty>No hay competidores habilitados en esta categoría todavía.</Empty>}{entries.map(e => <ScoreForm key={e.id + (s.scores.find(x => x.enrollmentId === e.id)?.submittedAt || "")} e={e} s={s} run={run} />)}</section>;
}
function ScoreForm({ e, s, run }: { e: Enrollment; s: Snapshot; run: Run }) {
  const existing = s.scores.find(x => x.enrollmentId === e.id); const [values, setValues] = useState<(number | "")[]>(existing?.values || CRITERIA.map(() => ""));
  const locked = existing?.locked; const total = values.reduce<number>((a, b) => a + (Number(b) || 0), 0); const complete = values.every(v => v !== "");
  return <div className="dance-panel"><div className="dance-panel-title"><div><p className="dance-eyebrow">{s.categories.find(c => c.id === e.categoryId)?.name}</p><h2>Competidor {String(e.competitionNumber).padStart(3, "0")}</h2></div><span className={`dance-badge ${locked ? "approved" : "pending"}`}>{locked ? "Enviada y bloqueada" : "Por calificar"}</span></div>{locked ? <><div className="dance-score-grid">{CRITERIA.map((c, i) => <div key={c}><span>{c}</span><strong>{values[i]}</strong></div>)}</div><div className="dance-score-total"><span>Total <strong>{total.toFixed(2)} / 60</strong></span><span>Promedio <strong>{(total / CRITERIA.length).toFixed(2)} / 10</strong></span></div><p className="dance-muted">Enviada {dateTime(existing!.submittedAt)}. Para corregirla, solicita autorización a la organización.</p></> : <Form action="score" run={run} label="Enviar y bloquear calificación"><input type="hidden" name="enrollmentId" value={e.id} /><input type="hidden" name="values" value={JSON.stringify(values)} /><div className="dance-score-grid">{CRITERIA.map((c, i) => <label key={c}><span>{c}</span><input aria-label={c} type="number" inputMode="decimal" min={1} max={10} step={0.1} value={values[i]} required onChange={event => { const next = [...values]; next[i] = event.target.value === "" ? "" : Number(event.target.value); setValues(next); }} /><small>De 1 a 10</small></label>)}</div><div className="dance-score-total"><span>Total <strong>{complete ? total.toFixed(2) : "—"} / 60</strong></span><span>Promedio <strong>{complete ? (total / CRITERIA.length).toFixed(2) : "—"} / 10</strong></span></div><label className="dance-check"><input type="checkbox" required /> Confirmo que estas notas corresponden a este número de competencia.</label></Form>}</div>;
}
