"use client";
import Link from "next/link";
import { useState } from "react";
import { statusLabels, money, dateTime, type Snapshot } from "@/lib/baile/types";
import { base, today, Heading, Empty, Badge, Stat, Form, Field, Receipt, Music, type Run } from "./ui";
export function Register({ s, run }: { s: Snapshot; run: Run }) {
  return <section className="dance-container dance-section"><Heading eyebrow="01 / Registro" title="Todo empieza con tu nombre." detail="Crea tu cuenta y después adjunta el comprobante de tu Full Pass desde tu panel." />{!s.settings.registrationOpen ? <Empty>Las inscripciones están cerradas.</Empty> : <div className="dance-two-columns"><div className="dance-panel"><Form action="register" run={run} label="Crear mi registro"><div className="dance-form-grid"><Field label="Nombre completo" name="name" autoComplete="name" maxLength={200} /><Field label="Número de documento" name="document" maxLength={30} /><Field label="Fecha de nacimiento" name="birthDate" type="date" max={today()} /><Field label="Ciudad / municipio" name="city" maxLength={200} /><Field label="Teléfono / WhatsApp" name="phone" type="tel" autoComplete="tel" maxLength={30} /><Field label="Correo electrónico" name="email" type="email" autoComplete="email" /><Field label="Academia o grupo" name="academy" required={false} maxLength={200} /><Field label="Contraseña (mínimo 10 caracteres)" name="password" type="password" minLength={10} maxLength={160} autoComplete="new-password" /></div><Field label="Información adicional para la organización" name="extra" required={false}><textarea name="extra" rows={3} maxLength={2000} placeholder="Cuéntanos si hay algo que debamos saber." /></Field><label className="dance-check"><input type="checkbox" name="consent" required /> Autorizo a la organización a usar estos datos para gestionar mi inscripción, pagos y participación en el evento.</label></Form></div><aside className="dance-panel dark"><p className="dance-eyebrow">TU ACCESO GENERAL</p><h2>Full Pass</h2><div className="dance-price">{money(s.settings.fullPassFee)}</div><p>Habilita tu participación y el acceso a las inscripciones por categoría cuando la organización apruebe el comprobante.</p><hr /><p>Las categorías tienen un pago independiente y puedes elegir más de una.</p><Link href={`${base}/acceso`}>Ya tengo cuenta ↗</Link></aside></div>}</section>;
}
function PaymentForm({ run, fee, enrollmentId = "" }: { run: Run; fee: number; enrollmentId?: string }) {
  return <Form action="payment" run={run} label="Enviar comprobante"><input type="hidden" name="enrollmentId" value={enrollmentId} /><div className="dance-form-grid"><Field label="Valor pagado (COP)" name="amount" type="number" min={fee} value={fee} /><Field label="Fecha del pago" name="date" type="date" max={today()} value={today()} /></div><Field label="Comprobante · PDF o imagen · máximo 5 MB" name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" /></Form>;
}
export function Participant({ s, run }: { s: Snapshot; run: Run }) {
  const p = s.participants[0]; const pass = s.payments.find(p => p.kind === "fullpass");
  const [selected, setSelected] = useState(""); const category = s.categories.find(c => c.id === selected);
  return <section className="dance-container dance-section"><Heading eyebrow={`MI ESPACIO / ${p.code}`} title={`Hola, ${p.name.split(" ")[0]}.`} detail="Aquí puedes seguir cada paso de tu participación." /><div className="dance-stats"><Stat label="Mi registro" value={statusLabels[pass?.status || "pending"]} /><Stat label="Categorías inscritas" value={s.enrollments.length} /><Stat label="Pistas cargadas" value={s.enrollments.filter(e => e.musicId).length} /></div><div className="dance-panel"><div className="dance-panel-title"><div><p className="dance-eyebrow">PASO 01</p><h2>Tu Full Pass</h2></div><Badge status={pass?.status} /></div><p className="dance-instructions">{s.settings.paymentInstructions}</p><p>Valor: <strong>{money(s.settings.fullPassFee)}</strong> · Registro: {dateTime(p.createdAt)}</p>{pass && <Receipt payment={pass} />}{pass?.status !== "approved" && <PaymentForm run={run} fee={s.settings.fullPassFee} />}</div>
    <div className="dance-panel"><p className="dance-eyebrow">PASO 02</p><h2>Inscripción a categorías</h2>{pass?.status !== "approved" ? <Empty>Cuando la organización apruebe tu Full Pass podrás elegir tus categorías.</Empty> : !s.settings.registrationOpen ? <Empty>Las nuevas inscripciones están cerradas.</Empty> : <Form action="enroll" run={run} label="Crear inscripción" after={() => setSelected("")}><Field label="Categoría" name="categoryId"><select name="categoryId" required value={selected} onChange={e => setSelected(e.target.value)}><option value="">Selecciona una categoría</option>{s.categories.filter(c => c.active && !s.enrollments.some(e => e.categoryId === c.id)).map(c => <option key={c.id} value={c.id}>{c.name} · {c.division} · {money(c.fee)}</option>)}</select></Field>{category && category.modality !== "Solista" ? <><Field label="Nombre de la pareja o grupo" name="team" maxLength={120} /><Field label="Nombres de los integrantes" name="members"><textarea name="members" required maxLength={2000} rows={3} /></Field></> : <><input name="team" type="hidden" value="" /><input name="members" type="hidden" value="" /></>}<p className="dance-muted">Cada inscripción tiene un comprobante, una pista y un número de competencia propios.</p></Form>}</div>
    <div className="dance-section-title"><h2>Mis competencias</h2><span>{s.enrollments.length} inscripciones</span></div>{!s.enrollments.length && <Empty>Tus categorías aparecerán aquí cuando te inscribas.</Empty>}{s.enrollments.map(e => { const c = s.categories.find(c => c.id === e.categoryId); const payment = s.payments.find(p => p.enrollmentId === e.id); const ready = payment?.status === "approved" && pass?.status === "approved"; const closed = c?.deadline && Date.now() > Date.parse(c.deadline); return <article className="dance-panel" key={e.id}><div className="dance-panel-title"><div><p className="dance-eyebrow">{e.code} · {c?.modality}</p><h2>{c?.name || "Categoría"}</h2><p>{c?.rhythm} · {c?.division}{e.team ? ` · ${e.team}` : ""}</p></div><div className="dance-competition-code"><small>NÚMERO DE COMPETENCIA</small><strong>{ready && e.competitionNumber ? String(e.competitionNumber).padStart(3, "0") : "Pendiente"}</strong></div></div><Receipt payment={payment} />{payment?.status !== "approved" && pass?.status === "approved" && <PaymentForm run={run} fee={e.fee} enrollmentId={e.id} />}<div className="dance-music-section"><h3>Pista musical de esta categoría</h3><Music e={e} />{!ready ? <p className="dance-muted">La carga se habilita cuando estén aprobados el Full Pass y el pago de esta categoría.</p> : closed ? <p className="dance-muted">El plazo de carga terminó el {dateTime(c!.deadline)}.</p> : <><p className="dance-muted">{c?.deadline ? `Puedes reemplazarla hasta ${dateTime(c.deadline)}.` : "Puedes reemplazarla mientras la organización mantenga abierto el plazo."}</p><Form action="music" run={run} label={e.musicId ? "Reemplazar pista" : "Cargar pista"}><input name="enrollmentId" type="hidden" value={e.id} /><Field label="Audio MP3, WAV, OGG o M4A · máximo 20 MB" name="file" type="file" accept=".mp3,.wav,.ogg,.m4a" /></Form></>}</div></article>; })}
  </section>;
}
